### ISSUE TITLE
More clarification on the data format

### ISSUE THREAD

**Issue by HanGuo97** [microsoft/task_oriented_dialogue_as_dataflow_synthesis#11]
Hi, thanks for the effort of open-sourcing the data and codes! I'm curious whether there is (or will be) more detailed documentation on the data provided. For example, what each of the data's fields represents and how are we supposed to use them. I'm having trouble locating this in the paper and the README, but feel free to point me to specific line numbers if I miss anything. Thanks in advance for the help!

**Comment by hao-fang** [comment]
Thanks for checking! At this moment we don't have a README for the format. But you can check the dataclass definitions [here](https://github.com/microsoft/task_oriented_dialogue_as_dataflow_synthesis/blob/1c48c1664947f498165756bce84b29a414eb8722/src/dataflow/core/dialogue.py#L88). We have some comments there to explain the fields.
Each line in the jsonl file is a `Dialogue`. 

Feel free to post here if you have more questions!

**Comment by HanGuo97** [comment]
Thanks, this is very helpful!

**Comment by HanGuo97** [comment]
Hi, just want to follow up on the issue on a slightly different question: could you explain what the model/task is here in a bit more detail? I read the paper but am still scratching my head to understand what each part of the codebase is trying to accomplish.

To be a bit more specific, here are some questions I have:
1. What is the model here trying to achieve? Using the terminology from [here](https://github.com/microsoft/task_oriented_dialogue_as_dataflow_synthesis/blob/1c48c1664947f498165756bce84b29a414eb8722/src/dataflow/core/dialogue.py#L88). Is the goal to generate `agent_utterance` given `user_utterance`?
2. I'm not super familiar with `OpenNMT`, but it seems like all the modeling part is handled by this library? If so, I'm curious about the role/functionalities of `src/dataflow/`, and in particular, `src/dataflow/core/`?

Thanks in advance for the help!

**Comment by hao-fang** [comment]
> 1. What is the model here trying to achieve? Using the terminology from [here](https://github.com/microsoft/task_oriented_dialogue_as_dataflow_synthesis/blob/1c48c1664947f498165756bce84b29a414eb8722/src/dataflow/core/dialogue.py#L88). Is the goal to generate `agent_utterance` given `user_utterance`?

The goal is to predict the program from the user utterance and its context turns.
In the experiments, we use the `Turn.lispress` field as the linearized representation of the [Program](https://github.com/microsoft/task_oriented_dialogue_as_dataflow_synthesis/blob/1c48c1664947f498165756bce84b29a414eb8722/src/dataflow/core/program.py#L43). You can use the [seq_to_program](https://github.com/microsoft/task_oriented_dialogue_as_dataflow_synthesis/blob/1c48c1664947f498165756bce84b29a414eb8722/src/dataflow/core/linearize.py#L21) and the [program_to_seq](https://github.com/microsoft/task_oriented_dialogue_as_dataflow_synthesis/blob/1c48c1664947f498165756bce84b29a414eb8722/src/dataflow/core/linearize.py#L26) method to convert between the lispress string and the `Program`.
You can see an example [here](https://github.com/microsoft/task_oriented_dialogue_as_dataflow_synthesis/blob/1c48c1664947f498165756bce84b29a414eb8722/tests/test_dataflow/core/test_linearize.py#L18).

> 2. I'm not super familiar with `OpenNMT`, but it seems like all the modeling part is handled by this library? If so, I'm curious about the role/functionalities of `src/dataflow/`, and in particular, `src/dataflow/core/`?

Yes, we use the off-the-shelf seq2seq model with copy mechanism in the OpenNMT for experiments since our paper focused on the novelty on the representation.
Our library provides two things: 1) methods to convert the `Program` in the released data to the linearized lispress format for seq2seq model, 2) convert MultiWOZ data to dataflow programs.

**Comment by HanGuo97** [comment]
Thanks for the very clear answers! (And sorry for another round of follow-up questions.)

To make sure I understand this correctly. All the codes under `src/dataflow/core/` are intended for converting `Program` to/from linearized lispress format?

* In that case, where does `agent_utterance` appear?
* According to Sec.7 in the paper, " program accuracy" is measured as "exact-match accuracy of the predicted program after inlining metacomputation." Does that mean the program itself would not be evaluated/executed, but will simply be compared the ground truth program (as opposed to, say, execute the program, and compare the program output)?
* What is the difference between "inline" and "dataflow" in Table 2 (and subsequently, README)? In the README, I wasn't able to find how to switch between these two modes, but likely I'm missing something.
* Related to the question above, do the models here all treat the `utterance -> program` as seq2seq (instead of other forms of structured prediction)?

**Comment by hao-fang** [comment]
> To make sure I understand this correctly. All the codes under `src/dataflow/core/` are intended for converting `Program` to/from linearized lispress format?

Right (and there are some other IO util methods).

> * In that case, where does `agent_utterance` appear?

The data comes with agent utterances, but we do not use them in our model and experiments.

> * According to Sec.7 in the paper, " program accuracy" is measured as "exact-match accuracy of the predicted program after inlining metacomputation." Does that mean the program itself would not be evaluated/executed, but will simply be compared the ground truth program (as opposed to, say, execute the program, and compare the program output)?

Correct.

> * What is the difference between "inline" and "dataflow" in Table 2 (and subsequently, README)? In the README, I wasn't able to find how to switch between these two modes, but likely I'm missing something.

There are two versions of data released. On this [page](https://microsoft.github.io/task_oriented_dialogue_as_dataflow_synthesis/), right below the "Data" button, you can find the link to the "inline" version.

> * Related to the question above, do the models here all treat the `utterance -> program` as seq2seq (instead of other forms of structured prediction)?

That's right.

**Comment by HanGuo97** [comment]
Thanks, these are quite clear!
