### ISSUE TITLE
regarding agent utterance

### ISSUE THREAD

**Issue by nikhil-iyer-97** [microsoft/task_oriented_dialogue_as_dataflow_synthesis#27]
Hi,

from reading the paper and looking at the training/valid data , I understand that the seq2seq model training is user_utterance -> program. I just want to know how to involve agent_utterance into the picture. Would be great if you could provide some tips regarding the same. Thanks!

**Comment by MathieuTuli** [comment]
If you run the preprocessing scripts, you can have a look at the files in `onmt_text_data_dir=output/onmt_text_data`. Take say `output/onmt_text_data/train.src`. You'll notice that each line is some combination `__User **user-utterance**` and `__StartOfProgram **program**` sequences. So here, the inputs to our model only contain the current user utterance plus some context length of previous user utterances and the associated ground truth program (teacher forcing is used so ground truth program would be used). As you say, the associated output sequence is just the next program to predict, which you see in `output/onmt_text_data/train.tgt`. All that to say, the agent utterances aren't included here for training. In this application, only the programs are used to build the contextualized inputs, I assume because they are richer in information (than agent utterance) and because our ultimate goal is for the agent to be able to extend/modify this program (computational graph), so having a reference of what it previously/currently looks like would be helpful.

That being said, agent utterance is often used to build the context in task-oriented dialogue x seq2seq. For example, you can have a look at this paper: [SimpleTOD](https://arxiv.org/pdf/2005.00796.pdf). It uses MultiWOZ, but look at pages 20-22, they show some examples of context (input to the model), and associated targets. In this case, they do use agent utterance to build the context for the model.

**Comment by nikhil-iyer-97** [comment]
Cool, thanks for the pointer to the paper too. It was very helpful. 👍
